### ISSUE TITLE
How to patch systray in Luke's build

### ISSUE THREAD

**Issue by LorenzoFoppiani** [mattkel/dwm#1]
I'm having a hard time patching [systray](https://dwm.suckless.org/patches/systray/) in [Luke's dwm build](https://github.com/LukeSmithxyz/dwm). His build is so heavily modified that it's not plug and play anymore, as expected. 
The first commit on this repo is of a DWM build very different from Luke's one, but what I'm trying to archieve here is just having Luke's build, with systray patched in. 

If you had a build like this floating around, or knew a way to just patch systray in, I'd be very grateful. Thanks

**Comment by mattkel** [comment]
This build is initially from Lukes dwm around 2 years ago, using dwm v6.2, so his current one is vastly different to how it used to be, and the one I'm using now. This build is heavily modified from Lukes current and past build from 2 years ago.

I mainly uploaded it here just so I have a backup of it, and I don't think it'll be easy for someone to use it as there's a few compiling errors and/or warnings that I can't be bothered to fix, as I'm not 100% fluent in C, but everything still just works, so I don't mind atm.

I have tried patching systray a few times using Lukes old builds from 2 years ago as well as a fresh install. The easiest way I found that resulted in little or no errors and having systray actually work, was to get a fresh dwm install with no patches, then apply systray, either through patch > p1 or manually (which is what I did and prefer), and then add your other patches from then on. 

I had a few issues, mostly when applying other patches that were also for the status bar (like winicon or awesomebar) that would override the systray code, so I had to get familiar enough with C to be able to figure that out/ remove some of them (awesomebar) - pretty sure it was all mostly in the drawbar function in dwm.c

Unfortunately I don't have a guide but that's pretty much how I got it to work, as well as a lot of trial and error. FYI the version of systray I used was 6.2 on their website, which was from 2020, and I see theres 3 newer versions now, and I haven't checked to see how much they differ.

Note also that I've been really lazy with the commenting, so there's little to no explanation as to what I changed or what something is doing, but you should be able to see the differences between a clean dwm build, Lukes, and mine with the systray patch and about 2 others in the drawbar function in dwm.c

Sorry I couldn't give you anything concrete to work with, I know how frustrating it is trying to get systray to work, especially with a heavily modified dwm or various status bar patches already installed.

**Comment by LorenzoFoppiani** [comment]
Alright, thanks man. Guess I'll start from vanilla DWM 6.2 and try and apply one patch at the time.

**Comment by LorenzoFoppiani** [comment]
I managed to get something working. It has most of the features I'm looking for (bar dwmblocks, for now), and has a working system tray. [LorenzoFoppiani/dwn](https://github.com/LorenzoFoppiani/dwm)
